set nocompatible
syntax on
filetype plugin indent on
set background=dark

call plug#begin()
Plug 'derekwyatt/vim-scala'
Plug 'flazz/vim-colorschemes'
Plug 'jiangmiao/auto-pairs'
Plug 'lervag/vimtex'
Plug 'mbbill/undotree'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-surround'
Plug 'Valloric/YouCompleteMe'
if has('win32')
    Plug 'xolox/vim-misc'
    Plug 'xolox/vim-shell'
endif
call plug#end()

set encoding=utf-8
let $LANG = 'en_US'
set guioptions-=m
set guioptions-=L
set guioptions-=r
set guioptions-=T

colorscheme Monokai
set guifont=Lucida_Console:h12:cANSI:qDRAFT

if has('win32')
    set lines=50
    set columns=140
endif

set backspace=indent,eol,start
set autoindent
set smartindent
set hlsearch
set incsearch
set gdefault
set number
set relativenumber
set wildmenu

set expandtab
set shiftwidth=0
set smarttab
set tabstop=4

nnoremap <silent> <BS> :nohlsearch<CR>
nnoremap <silent> Q :q<CR>
nnoremap <silent> <CR> :update<CR>
nnoremap <silent> H :bprevious<CR>
nnoremap <silent> L :bnext<CR>
nnoremap <silent> - :bdelete<CR>
nnoremap <silent> _ :bdelete!<CR>
nnoremap <silent> U :UndotreeToggle<CR>

nnoremap <C-C> <C-W><C-C>
nnoremap <C-H> <C-W><C-H>
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>

nnoremap <Left> <nop>
nnoremap <Right> <nop>
nnoremap <Up> <nop>
nnoremap <Down> <nop>
inoremap <Left> <nop>
inoremap <Right> <nop>
inoremap <Up> <nop>
inoremap <Down> <nop>

if has('win32')
    let g:ycm_global_ycm_extra_conf = 'C:/Users/baoji/vimfiles/ycm_extra_conf.py'
else
    let g:ycm_global_ycm_extra_conf = '~/.vim/ycm_extra_conf.py'
endif
let g:ycm_autoclose_preview_window_after_insertion = 1
let g:ycm_min_num_of_chars_for_completion          = 1
let g:ycm_seed_identifiers_with_syntax             = 1

augroup vimrc
    autocmd!

    autocmd BufReadPost *
                \ if line("'\"") >= 1 && line("'\"") <= line("$") |
                \   exe "normal! g`\"" |
                \ endif

augroup END
