if has('python3')
  silent! python3 1
endif

filetype plugin indent on
syntax on

let $LANG = 'en_US'
let mapleader = ','

set autoindent
set background=dark
set backspace=indent,eol,start
set encoding=utf-8
set expandtab
set gdefault
set guioptions-=L
set guioptions-=T
set guioptions-=m
set guioptions-=r
set hlsearch
set incsearch
set nocompatible
set number
set relativenumber
set shiftwidth=0
set smartindent
set smarttab
set tabstop=2
set timeoutlen=2000
set wildmenu

inoremap <Down> <nop>
inoremap <Left> <nop>
inoremap <Right> <nop>
inoremap <Up> <nop>
nnoremap <C-C> <C-W><C-C>
nnoremap <C-H> <C-W><C-H>
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <Down> <nop>
nnoremap <Left> <nop>
nnoremap <Right> <nop>
nnoremap <Up> <nop>
nnoremap <silent> - :bdelete<CR>
nnoremap <silent> <BS> :nohlsearch<CR>
nnoremap <silent> <CR> :w<CR>
nnoremap <silent> H gT
nnoremap <silent> L gt
nnoremap <silent> Q :q<CR>
nnoremap <silent> _ :bdelete!<CR>

call plug#begin()
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'airblade/vim-gitgutter'
Plug 'derekwyatt/vim-scala'
Plug 'digitaltoad/vim-pug'
Plug 'flazz/vim-colorschemes'
Plug 'jiangmiao/auto-pairs'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'lervag/vimtex'
Plug 'mattn/emmet-vim'
Plug 'mbbill/undotree'
Plug 'octol/vim-cpp-enhanced-highlight'
Plug 'pechorin/any-jump.vim'
Plug 'rdnetto/YCM-Generator', { 'branch': 'stable'}
Plug 'rhysd/vim-clang-format'
Plug 'scrooloose/nerdtree'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-surround'
if has('nvim')
  Plug 'alx741/vim-hindent'
  Plug 'autozimu/LanguageClient-neovim', { 'branch': 'next', 'do': 'bash install.sh' }
  Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() } }
  Plug 'mfulz/cscope.nvim'
  Plug 'neovimhaskell/haskell-vim'
else
  Plug 'vim-scripts/cscope.vim'
endif
if has('python') || has('python2') || has('python3')
  Plug 'Valloric/YouCompleteMe'
endif
if has('win32')
  Plug 'xolox/vim-misc'
  Plug 'xolox/vim-shell'
endif
call plug#end()

augroup vimrc
  autocmd!

  autocmd BufReadPost *
        \ if line("'\"") >= 1 && line("'\"") <= line("$") |
        \   exe "normal! g`\"" |
        \ endif

  if has('win32')
    autocmd GUIEnter * simalt ~x
  endif
augroup END
