#!/bin/bash

usage() {
    echo "Usage: doall {update|gpl|gs}"
}

doall() {
    pwdir=`pwd`
    if [[ ${1} == "update" ]]; then
        sudo apt update && sudo apt upgrade -y && sudo apt auto-remove -y && sudo apt auto-clean
        npm -g install npm
        npm -g update
        rustup update
        stack upgrade && stack update
    elif [[ ${1} == "gpl" ]]; then
        for dir in `ls`; do
            echo "********** Entering ${dir} **********"
            [[ -d ${dir} ]] && cd ${dir} && git pull
            cd ${pwdir}
            echo "********** Leaving ${dir} **********"
            echo " "
        done
    elif [[ ${1} == "gs" ]]; then
        for dir in `ls`; do
            echo "********** Entering ${dir} **********"
            [[ -d ${dir} ]] && cd ${dir} && git status
            cd ${pwdir}
            echo "********** Leaving ${dir} **********"
            echo " "
        done
    else
        usage && exit 0
    fi
}

[[ ${#} -ne 1 ]] && usage && exit 0
doall ${1}
