#!/bin/bash

usage() {
    echo "Usage: find_includes {cpp} <output_file>"
}

find_includes() {
    declare -A includes
    pwdir=`pwd`

    if [[ ${1} == "cpp" ]]; then
        totalFiles=`find . -name '*.c' -o -name '*.cpp' -o -name '*.h' -o -name '*.hpp' | wc -l`
        currentFiles=0
        echo "Total CPP related files found: ${totalFiles}"
        echo " "
        for file in `find . -name '*.c' -o -name '*.cpp' -o -name '*.h' -o -name '*.hpp'`; do
            while IFS= read -r line; do
                if [[ ${line} =~ \#include.*\".*\" ]]; then 
                    include=${line%\"*}
                    include=${include##*\"}
                    include=${include##*/}
                    for path in `find . -name ${include}`; do
                        dir=${path%/*}
                        [[ ${includes[${dir}]} ]] || includes[${dir}]=1
                    done
                fi
            done < ${file}
            currentFiles=$((${currentFiles} + 1))
            echo -en "\e[1A"; echo -e "\e[0K\rDone: ${currentFiles} == $((${currentFiles} * 100 / totalFiles))%"
        done

        rm -f ${2}
        for include in ${!includes[@]}; do
            echo ${pwdir}${include#*.} >> ${2}
        done
    fi
}

[[ ${#} -ne 2 ]] && usage && exit 1
find_includes ${1} ${2}
