#!/bin/bash

usage() {
    echo "Usage: find_includes {cpp} <output_file>"
}

find_includes() {
    declare -A includes
    pwdir=`pwd`

    if [[ ${1} == "cpp" ]]; then
        headers=`ag --cpp --cc '^ *#include.*\".*\" *' | grep -v \* | cut -d ':' -f 3 | cut -d '"' -f 2 | sort -u`
        totalFiles=`echo ${headers} | tr ' ' '\n' | wc -l`
        currentFiles=0
        echo "Total header files found: ${totalFiles}"
        echo " "
        for header in `echo ${headers}`; do
            for file in `find . -name ${header##*/}`; do
                dir=`dirname ${file}`
                [[ ${includes[${dir}]} ]] || includes[${dir}]=1
            done
            currentFiles=$((${currentFiles} + 1))
            echo -en "\e[1A"; echo -e "\e[0K\rDone: ${currentFiles} == $((${currentFiles} * 100 / totalFiles))%"
        done

        rm -f ${2}
        for include in ${!includes[@]}; do
            echo ${pwdir}${include#*.} >> ${2}
        done
    fi
}

[[ ${#} -ne 2 ]] && usage && exit 1
find_includes ${1} ${2}
