#!/bin/zsh

exists() {
  if (( $+commands[$1] )); then return 0; else return 1; fi
}

calc() {
  awk "BEGIN{ print $* }" ;
}

# lists zombie processes
zombie() {
  ps aux | awk '{if ($8=="Z") { print $2 }}'
}
