#!/bin/bash
#
# Only including a shebang to trigger Sublime Text to use shell syntax highlighting
#
# Copyright 2006-2018 Joseph Block <jpb@unixorn.net>
#
# BSD licensed, see LICENSE.txt in this repository.

alias sudo='sudo '

alias ls='ls --color=auto -h'
alias la='ls -a'
alias lal='ls -al'
alias ll='ls -l'

alias -- +x='chmod +x'
alias -- -x='chmod -x'
alias mkdir='mkdir -pv'
alias rm='rm -Iv'

# git
alias ga='git add'
alias gb='git branch'
alias gc='git commit'
alias gcb='git checkout -b'
alias gce='git commit --allow-empty-message -m ""'
alias gch='git checkout'
alias gd='git diff'
alias gdc='git diff --cached'
alias gf='git fetch'
alias gl='git log'
alias gm='git merge --no-edit'
alias gpl='git pull'
alias gps='git push'
alias gr='git reset'
alias gs='git status'
alias gsd='git stash drop'
alias gsp='git stash pop'
alias gss='git stash save'

# svn
alias sa='svn add'
alias sb='svn blame'
alias sc='svn commit'
alias sch='svn checkout'
alias sd='svn diff'
alias sl='svn log'
alias slv='svn log -vl'
alias sm='svn merge --non-interactive --ignore-ancestry'
alias sr='svn revert'
alias srm="svn status | grep '^?' | awk '{print $2}' | xargs rm -rf"
alias srr='svn revert -R'
alias ss='svn status'
alias ssq='svn status --quiet'
alias sup='svn update'

alias historysummary="history | awk '{a[\$2]++} END{for(i in a){printf \"%5d\t%s\n\",a[i],i}}' | sort -rn | head"

# A couple of different external IP lookups depending on which is down.
alias extip="curl -s icanhazip.com"
alias myip="dig +short myip.opendns.com @resolver1.opendns.com"

# Show laptop's IP addresses
alias ips="ifconfig -a | perl -nle'/(\d+\.\d+\.\d+\.\d+)/ && print $1'"

# SSH stuff
# Pass our credentials by default
alias ssh='ssh -A'
alias sshA='ssh -A'
alias ssh_unkeyed='/usr/bin/ssh'

alias scp_no_hostchecks='scp -o UserKnownHostsFile=/dev/null -o GlobalKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
alias ssh_no_hostchecks='ssh -A -o UserKnownHostsFile=/dev/null -o GlobalKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'

# Set up even more shortcuts because I am that lazy a typist.
alias nh_scp=scp-no-hostchecks
alias nh_ssh=ssh-no-hostchecks
alias nhscp=scp-no-hostchecks
alias nhssh=ssh-no-hostchecks

# Strip color codes from commands that insist on spewing them so we can
# pipe them into files cleanly.
alias stripcolors='sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g"'

# On the rare occasions I don't want to continue an interrupted download
# I can always delete the incomplete fragment explicitly. I usually just
# want to complete it.
alias wget="wget -c"

# Dump the last 20 history entries to make !number more convenient to use.
alias zh="fc -l -d -D"

# My typical tyops.
alias gerp='grep'
alias grep-i='grep -i'
alias grep='GREP_COLOR="1;37;41" LANG=C grep --color=auto'
alias grepi='grep -i'
alias knfie='knife'
alias maek='make'
alias psax='ps ax'
alias pswax='ps wax'
alias psxa='ps ax'
alias raek='rake'
alias tartvf='tar tvf'
alias tartvzf='tar tvzf'
alias tarxvf='tar xvf'

# Help the lazy typists again.
alias ..="cd .."
