# vim: ft=sh

[[ $- != *i* ]] && return

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User alias
alias sudo="sudo "

alias ls="ls --color=auto -h"
alias la="ls -a"
alias lal="ls -al"
alias ll="ls -l"

alias -- +x="chmod +x"
alias -- -x="chmod -x"
alias mkdir="mkdir -pv"
alias rm="rm -Iv"

alias grep="grep --color=auto"

alias ga="git add"
alias gb="git branch"
alias gc="git commit"
alias gcb="git checkout -b"
alias gce="git commit --allow-empty-message -m ''"
alias gch="git checkout"
alias gd="git diff"
alias gdc="git diff --cached"
alias gf="git fetch"
alias gl="git log"
alias gm="git merge --no-edit"
alias gpl="git pull"
alias gps="git push"
alias gr="git reset"
alias gs="git status"
alias gsd="git stash drop"
alias gsp="git stash pop"
alias gss="git stash save"

alias_path=~/.settings/alias
if [[ -f $alias_path ]]; then
    source $alias_path
fi

# Function
mkcd() {
    mkdir -p -- "$1" &&
        cd -- "$1"
}

function_path=~/.settings/function
if [[ -f $function_path ]]; then
    source $function_path
fi
